language: python
python:
  - 3.6
os:
  - linux
git:
  depth: 1
before_install:
  - pip install pip --upgrade
install:
  - make venv
  - source ./.venv/rastrea2r_server/bin/activate
  
script:
  - make test
  - make check-coverage
  - make docs

