version: 1
update_configs:
  - package_manager: "python"
    directory: "/"
    update_schedule: "live"
    target_branch: "master"
    default_assignees: ["ssbhat"]
    default_reviewers: ["ssbhat"]

